{% set name = "injector" %}
{% set version = "0.23.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/injector-{{ version }}.tar.gz
  sha256: 7e59db84faa5358474c8ee05abca6ab6bd02519fbefcf175e0b230ee7d2d4bac

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pypandoc
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - typing_extensions >=3.7.4

test:
  imports:
    - injector
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/alecthomas/injector
  summary: Injector - Python dependency injection framework, inspired by Guice
  license: BSD-3-Clause
  # License file manually packaged: See: https://github.com/alecthomas/injector/pull/160
  license_file: COPYING

extra:
  recipe-maintainers:
    - fuglede
